# Generated by Django 5.2.2 on 2026-08-15 02:09

import django.db.models.deletion
from django.db import migrations, models


def set_base_origen(apps, schema_editor):
    Precios = apps.get_model('pozosscz', 'PreciosPozosSCZ')
    BaseCamion = apps.get_model('pozosscz', 'BaseCamion')
    base = BaseCamion.objects.filter(deleted=False, name__icontains='saguapac').first()
    if base:
        Precios.objects.filter(base_origen__isnull=True).update(base_origen=base)


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0038_datosgenerales_hero_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciospozosscz',
            name='base_origen',
            field=models.ForeignKey(blank=True, help_text='Base única desde donde parte el camión al cotizar. Si está vacía se usa Saguapac.', limit_choices_to={'deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pozosscz.basecamion', verbose_name='Base de origen'),
        ),
        migrations.RunPython(set_base_origen, migrations.RunPython.noop),
    ]
