# Generated by Django 5.2.2 on 2026-08-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_cliente_indexes_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('COT', 'Cotizado'), ('PRG', 'Programado'), ('EJE', 'Ejecutado'), ('CAN', 'Cancelado'), ('NEG', 'L.negra'), ('WEB', 'Web')], default='COT', max_length=3, verbose_name='estado'),
        ),
    ]
